Repository ThreatConnect-Inc/tcex, pull requests merged in 2022-01, with the labels that each got.

#145 Updates for beta 2
  .cspell/custom-dictionary-workspace.txt
  .github/workflows/codeql-analysis.yml
  .github/workflows/main.yml
  README.md
  bin/tcex
  release_notes.md
  setup.py
  tcex/__metadata__.py
  tcex/app_config/models/install_json_model.py
  tcex/bin/dep.py
  tcex/bin/validate.py
  tests/app_config/test_install_json_model.py
Labels: enhancement

#148 Develop
  tcex/app_config/models/job_json_model.py
  tcex/exit/exit.py
Labels: bug, enhancement

#149 Develop
  tcex/api/tc/v3/v3_model_abc.py
Labels: bug

#153 APP-3347 don't retain existing content in message.tc. APP-3370 add -…
  bin/tcex
  tcex/bin/dep.py
  tcex/exit/exit.py
Labels: enhancement

#154 + update bandit dep for python 3.6
  setup.py
Labels: enhancement

#155 Develop
  tcex/api/tc/v2/batch/batch_writer.py
  tcex/api/tc/v2/batch/group.py
Labels: enhancement

#158 TcEx Deploy and Sensitive logging updates
  .cspell/custom-dictionary-workspace.txt
  bin/tcex
  tcex/bin/deploy.py
  tcex/input/field_types/sensitive.py
  tcex/logger/logger.py
  tcex/logger/sensitive_filter.py
  tests/input/field_types/utils.py
Labels: enhancement

#159 Testing Updates
  .cspell/custom-dictionary-workspace.txt
  .github/workflows/main.yml
  setup.cfg
  tcex/api/tc/v2/batch/batch.py
  tcex/input/field_types/edit_choice.py
  tcex/input/models/model_map.py
  tests/README.md
  tests/api/tc/v3/cases/test_case_interface.py
  tests/api/tc/v3/groups/test_group_interface.py
  tests/api/tc/v3/indicators/test_indicator_interface.py
  tests/app_config/test_install_json_model.py
  tests/app_config/test_layout_json_model.py
  tests/app_config/test_permutations.py
  tests/app_config/test_tcex_json_model.py
  tests/bin/test_tcex_deps.py
  tests/bin/test_tcex_init.py
  tests/bin/test_tcex_list.py
  tests/conftest.py
  tests/input/test_inputs.py
  tests/mock_app.py
Labels: enhancement
