Repository ThreatConnect-Inc/tcex, pull requests merged in 2022-03, with the labels that each got.

#188 - updates to spectool to better support service Apps.
  tcex/app_config/install_json_update.py
  tcex/app_config/models/app_spec_yml_model.py
  tcex/bin/spec_tool_app_input.py
  tcex/bin/spec_tool_app_input_static.py
Labels: enhancement

#194 Minor update to spectool
  tcex/app_config/app_spec_yml.py
  tcex/app_config/models/app_spec_yml_model.py
Labels: enhancement

#195 Changes to github actions
  .github/workflows/main.yml
Labels: enhancement

#197 Minor updates for spectool
  tcex/app_config/app_spec_yml.py
  tcex/app_config/models/app_spec_yml_model.py
  tcex/app_config/models/install_json_model.py
  tcex/bin/spec_tool_readme_md.py
  tests/README.md
Labels: enhancement

#198 Cleanup and fixes for spectool
  MANIFEST.in
  setup.py
  tcex/app_config/permutation.py
  tcex/bin/spec_tool_app_input.py
  tests/rerun_failed_test.py
Labels: bug

#199 Bumped version, updated release notes, fixed issue for spectool with job App configs
  release_notes.md
  tcex/__metadata__.py
  tcex/app_config/models/app_spec_yml_model.py
Labels: bug

#202 fixing resultLimit issue when len() is called on object_collection
  tcex/api/tc/v3/object_collection_abc.py
Labels: bug

#204 Code cleanup, bug fixes
  bin/tcex
  release_notes.md
  tcex/__metadata__.py
  tcex/app_config/app_spec_yml.py
  tcex/app_config/models/app_spec_yml_model.py
  tcex/app_config/models/install_json_model.py
  tcex/bin/spec_tool_app_input.py
  tcex/input/field_types/integer.py
  tcex/input/field_types/ip_address.py
  tcex/input/field_types/sensitive.py
  tcex/input/field_types/string.py
  tcex/logger/rotating_file_handler_custom.py
  tcex/sessions/external_session.py
  tcex/sessions/tc_session.py
  tcex/tcex.py
Labels: bug, enhancement

#207 Develop
  tcex/api/tc/v3/_gen/_gen_model_abc.py
  tcex/api/tc/v3/_gen/_gen_object_abc.py
  tcex/api/tc/v3/artifact_types/artifact_type.py
  tcex/api/tc/v3/artifacts/artifact.py
  tcex/api/tc/v3/cases/case.py
  tcex/api/tc/v3/groups/group.py
  tcex/api/tc/v3/indicators/indicator.py
  tcex/api/tc/v3/notes/note.py
  tcex/api/tc/v3/security/user_groups/user_group.py
  tcex/api/tc/v3/security/users/user.py
  tcex/api/tc/v3/tasks/task.py
  tcex/api/tc/v3/tasks/task_model.py
  tcex/api/tc/v3/victims/victim.py
  tcex/api/tc/v3/workflow_events/workflow_event.py
  tcex/api/tc/v3/workflow_templates/workflow_template.py
  tcex/api/tc/v3/workflow_templates/workflow_template_model.py
  tcex/decorators/on_exception.py
  tcex/input/field_types/case_management_entity.py
  tcex/input/field_types/validators.py
  tests/app_config/apps/tcpb/app_1/app_inputs.py
  tests/input/field_types/test_field_type_ip_address.py
Labels: bug

#209 Fix logging to use model value
  tcex/bin/validate.py
Labels: bug

#215 APP-3454 Fix retry conversion in spec tool
  tcex/bin/spec_tool_install_json.py
Labels: bug
